name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: SPTKL/action-library@main
        env: 
          RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: edm-recipes
        with:
          name: bpl_libraries
