name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    env: 
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: edm-recipes
    steps:
      - uses: SPTKL/action-library@main
        id: process
        with:
          name: dcp_commercialoverlay
          latest: true
          s3: true
          compress: true
          output_format: shapefile csv pgdump
     
      - uses: SPTKL/action-library@main
        id: process2
        with:
          name: nypl_libraries
          latest: true
          s3: true
          compress: true
          output_format: shapefile csv pgdump

      - name: show output
        run: |
          echo "${{ steps.process.outputs.show }}"
          echo "${{ steps.process2.outputs.show }}"

          
